on:
  workflow_dispatch:

name: Release install.sh

jobs:
  release-install-script:
    name: Releasing install script
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::901443922744:role/github_actions

      - name: Upload install script to S3
        run: |
          aws s3 cp \
            --acl public-read \
            scripts/install.sh \
            s3://fp.dev/install.sh

      - name: Invalidate install script on CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "${{ secrets.CF_BUILDS_ID }}" \
            --paths '/install.sh'
