name: Assign weekly release dependabot reviewer
on:
  pull_request:
    types:
      - opened
      - ready_for_review

jobs:
  assign:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    permissions: write-all
    steps:
      - name: assign dependency updates team to pull request
        env:
          GH_TOKEN: ${{ secrets.PRIVATE_GITHUB_TOKEN }}
          url: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr edit "$url" --add-reviewer fiberplane/cli-devs-dependency-updates
