name: Assign weekly release dependabot reviewer
on:
  pull_request:
    branches:
      - "dependabot/*"
    types:
      - opened
      - ready_for_review

permissions:
  pull-requests: write

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: assign dependency updates team to pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          url: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr edit "$url" --add-reviewer fiberplane/cli-devs-dependency-updates
